version: '3.7'

services:

  postgres-employee-app:
    image: postgres:11.4-alpine
    hostname: postgres-employee-app
    env_file:
      - .env
    shm_size: '100'
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=10MB
      -c statement_timeout=180000
    tmpfs:
      - /tmp:size=10M
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
      - 5457:5432
    networks:
      - employee-app-network

  rabbitmq-employee-app:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-employee-app
    env_file:
      - .env
    ports:
      - 5671:5672
      - 15671:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - employee-app-network

volumes:
  db-data:
    driver: local

networks:
  employee-app-network:
    driver: bridge